# Generated by Django 4.2.3 on 2023-11-20 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pongue', '0002_pongueuser_delete_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pongueuser',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
