# Generated by Django 4.2.3 on 2023-11-20 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pongue', '0003_alter_pongueuser_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='pongueuser',
            name='has_2fa',
            field=models.BooleanField(default=False),
        ),
    ]
