# Generated by Django 4.2.3 on 2024-09-08 16:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pongue', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('isRead', models.BooleanField(default=False)),
                ('message', models.TextField()),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pongue.playerfriend')),
                ('senderId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('chatName', models.CharField(default=None, max_length=50)),
                ('chatType', models.CharField(default=None, max_length=50)),
                ('chatMembers', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='chatMembers', to='pongue.playerfriend')),
            ],
        ),
    ]
