# Generated by Django 4.2.3 on 2024-09-11 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('chatName', models.CharField(default=None, max_length=50)),
                ('chatType', models.CharField(default=None, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('isRead', models.BooleanField(default=False)),
                ('message', models.TextField()),
            ],
        ),
    ]
