# Generated by Django 4.2.3 on 2024-09-09 17:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pongue', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='chat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pongue.playerfriend'),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='senderId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='chat',
            name='chatMembers',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='chatMembers', to='pongue.playerfriend'),
        ),
    ]
