# Generated by Django 4.2.3 on 2024-07-18 11:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pongue', '0006_alter_pongueuser_friends'),
        ('chat', '0002_rename_is_deleted_chatmessage_isread_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessage',
            name='chat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pongue.playerfriend'),
        ),
    ]
